# .github/workflows/build-and-push.yml

# Name of the workflow
name: Build and Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-push"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Check-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to your private Docker registry
      #    Uses secrets to avoid exposing credentials in the code.
      # - name: Log in to the container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.home-lab.ir
      #     username: ${{ secrets.REGISTRY_USER }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      # 3. Extract the short commit hash to use as the image tag
      - name: Extract short commit hash
        id: vars # Give this step an ID to reference its outputs
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      # 4. Build the Docker image and push it to the registry.
      #    The image is tagged with the short commit hash.
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.home-lab.ir/simanban/admin-front:${{ steps.vars.outputs.sha_short }}
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ env.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY }}
